# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177rhoci0_QbEkmyFn39Hp2rbYH_cIKmW
"""

a = int(input("Birinchi sonni kiriting: "))
b = int(input("Ikkinchi sonni kiriting: "))

print("Qo'shish:", a + b)
print("Ayirish:", a - b)
print("Ko'paytirish:", a * b)
print("Bo'lish:", a / b)